server:
  port: 9006
spring:
  application:
    name: schedule-service

basic:
  data: http://localhost:9000
---

data:
  cache: http://localhost:9005
---

ribbon:
  eureka:
    enabled: false
data-cache:
  ribbon:
    listOfServers: localhost:9005
basic-data:
  ribbon:
    listOfServers: localhost:9000