server:
  port: 9006
spring:
  application:
    name: schedule-service
#  datasource:
#         #数据库相关的配置url -SSL连接设置为false
#    url: jdbc:mysql://localhost:3306/fleet-log?useSSL=false
#         #配置用户名
#    username: root
#         #配置密码
#    password: root
#    tomcat:
#      max-active: 100
#      max-idle: 200
#      initialSize: 20
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect

basic:
  data: http://localhost:9000
---

data:
  cache: http://localhost:9005
---

fleet:
  simulator: http://localhost:9007
---

ribbon:
  eureka:
    enabled: false
data-cache:
  ribbon:
    listOfServers: localhost:9005
basic-data:
  ribbon:
    listOfServers: localhost:9000


