server:
  port: 9000
spring:
  application:
    name: basic-data
#    #数据源和jpa配置
#  datasource:
#     #数据库相关的配置url -SSL连接设置为false
#    url: jdbc:mysql://localhost:3306/fleet-basic?useSSL=false
#     #配置用户名
#    username: root
#     #配置密码
#    password: root
#    tomcat:
#      max-active: 100
#      max-idle: 200
#      initialSize: 20
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect